// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ffmpeg.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	pb "m7s.live/v5/pb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FFmpegProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	AutoStart     bool                   `protobuf:"varint,6,opt,name=autoStart,proto3" json:"autoStart,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FFmpegProcess) Reset() {
	*x = FFmpegProcess{}
	mi := &file_ffmpeg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FFmpegProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FFmpegProcess) ProtoMessage() {}

func (x *FFmpegProcess) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FFmpegProcess.ProtoReflect.Descriptor instead.
func (*FFmpegProcess) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{0}
}

func (x *FFmpegProcess) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FFmpegProcess) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FFmpegProcess) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *FFmpegProcess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FFmpegProcess) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FFmpegProcess) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

func (x *FFmpegProcess) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FFmpegProcess) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	AutoStart     bool                   `protobuf:"varint,3,opt,name=autoStart,proto3" json:"autoStart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessRequest) Reset() {
	*x = CreateProcessRequest{}
	mi := &file_ffmpeg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessRequest) ProtoMessage() {}

func (x *CreateProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessRequest.ProtoReflect.Descriptor instead.
func (*CreateProcessRequest) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProcessRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProcessRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *CreateProcessRequest) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

type UpdateProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	AutoStart     bool                   `protobuf:"varint,4,opt,name=autoStart,proto3" json:"autoStart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcessRequest) Reset() {
	*x = UpdateProcessRequest{}
	mi := &file_ffmpeg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessRequest) ProtoMessage() {}

func (x *UpdateProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessRequest.ProtoReflect.Descriptor instead.
func (*UpdateProcessRequest) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProcessRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProcessRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProcessRequest) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *UpdateProcessRequest) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

type ProcessIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessIdRequest) Reset() {
	*x = ProcessIdRequest{}
	mi := &file_ffmpeg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessIdRequest) ProtoMessage() {}

func (x *ProcessIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessIdRequest.ProtoReflect.Descriptor instead.
func (*ProcessIdRequest) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *FFmpegProcess         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_ffmpeg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessResponse) GetData() *FFmpegProcess {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*FFmpegProcess       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_ffmpeg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{5}
}

func (x *ListProcessesResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListProcessesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListProcessesResponse) GetData() []*FFmpegProcess {
	if x != nil {
		return x.Data
	}
	return nil
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_ffmpeg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ffmpeg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_ffmpeg_proto_rawDescGZIP(), []int{6}
}

func (x *VersionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VersionResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_ffmpeg_proto protoreflect.FileDescriptor

const file_ffmpeg_proto_rawDesc = "" +
	"\n" +
	"\fffmpeg.proto\x12\x06ffmpeg\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fglobal.proto\"\x9b\x02\n" +
	"\rFFmpegProcess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x1c\n" +
	"\tautoStart\x18\x06 \x01(\bR\tautoStart\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\x14CreateProcessRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12\x1c\n" +
	"\tautoStart\x18\x03 \x01(\bR\tautoStart\"\x84\x01\n" +
	"\x14UpdateProcessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x1c\n" +
	"\tautoStart\x18\x04 \x01(\bR\tautoStart\"\"\n" +
	"\x10ProcessIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"j\n" +
	"\x0fProcessResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.ffmpeg.FFmpegProcessR\x04data\"p\n" +
	"\x15ListProcessesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.ffmpeg.FFmpegProcessR\x04data\"S\n" +
	"\x0fVersionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2\xa6\x06\n" +
	"\x03api\x12e\n" +
	"\rCreateProcess\x12\x1c.ffmpeg.CreateProcessRequest\x1a\x17.ffmpeg.ProcessResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/ffmpeg/api/create\x12j\n" +
	"\rUpdateProcess\x12\x1c.ffmpeg.UpdateProcessRequest\x1a\x17.ffmpeg.ProcessResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/ffmpeg/api/update/{id}\x12c\n" +
	"\rDeleteProcess\x12\x18.ffmpeg.ProcessIdRequest\x1a\x17.global.SuccessResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/ffmpeg/api/delete/{id}\x12`\n" +
	"\rListProcesses\x12\x16.google.protobuf.Empty\x1a\x1d.ffmpeg.ListProcessesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/ffmpeg/api/list\x12a\n" +
	"\fStartProcess\x12\x18.ffmpeg.ProcessIdRequest\x1a\x17.global.SuccessResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/ffmpeg/api/start/{id}\x12_\n" +
	"\vStopProcess\x12\x18.ffmpeg.ProcessIdRequest\x1a\x17.global.SuccessResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x15/ffmpeg/api/stop/{id}\x12e\n" +
	"\x0eRestartProcess\x12\x18.ffmpeg.ProcessIdRequest\x1a\x17.global.SuccessResponse\" \x82\xd3\xe4\x93\x02\x1a\"\x18/ffmpeg/api/restart/{id}\x12Z\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\x17.ffmpeg.VersionResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/ffmpeg/api/versionB\x1eZ\x1cm7s.live/v5/plugin/ffmpeg/pbb\x06proto3"

var (
	file_ffmpeg_proto_rawDescOnce sync.Once
	file_ffmpeg_proto_rawDescData []byte
)

func file_ffmpeg_proto_rawDescGZIP() []byte {
	file_ffmpeg_proto_rawDescOnce.Do(func() {
		file_ffmpeg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ffmpeg_proto_rawDesc), len(file_ffmpeg_proto_rawDesc)))
	})
	return file_ffmpeg_proto_rawDescData
}

var file_ffmpeg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ffmpeg_proto_goTypes = []any{
	(*FFmpegProcess)(nil),         // 0: ffmpeg.FFmpegProcess
	(*CreateProcessRequest)(nil),  // 1: ffmpeg.CreateProcessRequest
	(*UpdateProcessRequest)(nil),  // 2: ffmpeg.UpdateProcessRequest
	(*ProcessIdRequest)(nil),      // 3: ffmpeg.ProcessIdRequest
	(*ProcessResponse)(nil),       // 4: ffmpeg.ProcessResponse
	(*ListProcessesResponse)(nil), // 5: ffmpeg.ListProcessesResponse
	(*VersionResponse)(nil),       // 6: ffmpeg.VersionResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
	(*pb.SuccessResponse)(nil),    // 9: global.SuccessResponse
}
var file_ffmpeg_proto_depIdxs = []int32{
	7,  // 0: ffmpeg.FFmpegProcess.createdAt:type_name -> google.protobuf.Timestamp
	7,  // 1: ffmpeg.FFmpegProcess.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: ffmpeg.ProcessResponse.data:type_name -> ffmpeg.FFmpegProcess
	0,  // 3: ffmpeg.ListProcessesResponse.data:type_name -> ffmpeg.FFmpegProcess
	1,  // 4: ffmpeg.api.CreateProcess:input_type -> ffmpeg.CreateProcessRequest
	2,  // 5: ffmpeg.api.UpdateProcess:input_type -> ffmpeg.UpdateProcessRequest
	3,  // 6: ffmpeg.api.DeleteProcess:input_type -> ffmpeg.ProcessIdRequest
	8,  // 7: ffmpeg.api.ListProcesses:input_type -> google.protobuf.Empty
	3,  // 8: ffmpeg.api.StartProcess:input_type -> ffmpeg.ProcessIdRequest
	3,  // 9: ffmpeg.api.StopProcess:input_type -> ffmpeg.ProcessIdRequest
	3,  // 10: ffmpeg.api.RestartProcess:input_type -> ffmpeg.ProcessIdRequest
	8,  // 11: ffmpeg.api.GetVersion:input_type -> google.protobuf.Empty
	4,  // 12: ffmpeg.api.CreateProcess:output_type -> ffmpeg.ProcessResponse
	4,  // 13: ffmpeg.api.UpdateProcess:output_type -> ffmpeg.ProcessResponse
	9,  // 14: ffmpeg.api.DeleteProcess:output_type -> global.SuccessResponse
	5,  // 15: ffmpeg.api.ListProcesses:output_type -> ffmpeg.ListProcessesResponse
	9,  // 16: ffmpeg.api.StartProcess:output_type -> global.SuccessResponse
	9,  // 17: ffmpeg.api.StopProcess:output_type -> global.SuccessResponse
	9,  // 18: ffmpeg.api.RestartProcess:output_type -> global.SuccessResponse
	6,  // 19: ffmpeg.api.GetVersion:output_type -> ffmpeg.VersionResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ffmpeg_proto_init() }
func file_ffmpeg_proto_init() {
	if File_ffmpeg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ffmpeg_proto_rawDesc), len(file_ffmpeg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ffmpeg_proto_goTypes,
		DependencyIndexes: file_ffmpeg_proto_depIdxs,
		MessageInfos:      file_ffmpeg_proto_msgTypes,
	}.Build()
	File_ffmpeg_proto = out.File
	file_ffmpeg_proto_goTypes = nil
	file_ffmpeg_proto_depIdxs = nil
}
