// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: logrotate.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogrotateClient is the client API for Logrotate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogrotateClient interface {
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponseFileInfo, error)
	Get(ctx context.Context, in *RequestFileInfo, opts ...grpc.CallOption) (*ResponseOpen, error)
}

type logrotateClient struct {
	cc grpc.ClientConnInterface
}

func NewLogrotateClient(cc grpc.ClientConnInterface) LogrotateClient {
	return &logrotateClient{cc}
}

func (c *logrotateClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResponseFileInfo, error) {
	out := new(ResponseFileInfo)
	err := c.cc.Invoke(ctx, "/m7s.logrotate/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logrotateClient) Get(ctx context.Context, in *RequestFileInfo, opts ...grpc.CallOption) (*ResponseOpen, error) {
	out := new(ResponseOpen)
	err := c.cc.Invoke(ctx, "/m7s.logrotate/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogrotateServer is the server API for Logrotate service.
// All implementations must embed UnimplementedLogrotateServer
// for forward compatibility
type LogrotateServer interface {
	List(context.Context, *emptypb.Empty) (*ResponseFileInfo, error)
	Get(context.Context, *RequestFileInfo) (*ResponseOpen, error)
	mustEmbedUnimplementedLogrotateServer()
}

// UnimplementedLogrotateServer must be embedded to have forward compatible implementations.
type UnimplementedLogrotateServer struct {
}

func (UnimplementedLogrotateServer) List(context.Context, *emptypb.Empty) (*ResponseFileInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLogrotateServer) Get(context.Context, *RequestFileInfo) (*ResponseOpen, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLogrotateServer) mustEmbedUnimplementedLogrotateServer() {}

// UnsafeLogrotateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogrotateServer will
// result in compilation errors.
type UnsafeLogrotateServer interface {
	mustEmbedUnimplementedLogrotateServer()
}

func RegisterLogrotateServer(s grpc.ServiceRegistrar, srv LogrotateServer) {
	s.RegisterService(&Logrotate_ServiceDesc, srv)
}

func _Logrotate_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogrotateServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m7s.logrotate/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogrotateServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logrotate_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogrotateServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m7s.logrotate/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogrotateServer).Get(ctx, req.(*RequestFileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Logrotate_ServiceDesc is the grpc.ServiceDesc for Logrotate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logrotate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "m7s.logrotate",
	HandlerType: (*LogrotateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Logrotate_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Logrotate_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logrotate.proto",
}
